stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t rq-bot -f MainTask/Dockerfile .
  only:
    - main

test:
  stage: test
  image: python:3.12-slim
  script:
    - pip install pytest PyMuPDF google-generativeai
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/MainTask
    - pytest
  only:
    - main
