stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t rq-bot -f MainTask/Dockerfile .
  only:
    - main

test:
  stage: test
  image: rq-bot
  script:
    - pytest
  only:
    - main