stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t rq-bot -f MainTask/Dockerfile .
  only:
    - main

test:
  stage: test
  image: python:3.12-slim
  script:
    - pip install -r MainTask/requirements.txt
    - pytest MainTask/
  only:
    - main